version: '3.12'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/mount/qdrant_storage:/qdrant/storage

  aime-agenticrag:
    image: aime-agenticrag
    ports:
      - "8088:8088"
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_COLLECTION_NAME=${QDRANT_COLLECTION_NAME}
      - HF_HOME=${HF_HOME}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES}
      - CELERY_APP_NAME=${CELERY_APP_NAME}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    depends_on:
      - qdrant